@baseURL=http://localhost:3333
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNGE2YWY4Zi1lMDEyLTRmMGMtODQxZC05NzJmYmM3MWNlMzgiLCJpYXQiOjE3MTEzNzE3NjUsImV4cCI6MTcxMTM3MjM2NX0.RfU7mCMHClE8ASyYbR9MPdJkNzxzfJGCuVQWHl7s7bY

### Create a Organization
POST {{baseURL}}/organizations
Content-Type: application/json

{
  "address": "Rua José Boschetti, 268",
  "zipcode": "95040420",
  "whatsapp": "54999859934",
  "responsible": "Pedro Alberto Veber Berna",
  "email": "pedro.veber@outlook.com",
  "password": "pe991007"
}

### Authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "pedro.veber@outlook.com",
  "password": "pe991007"
}

### Create a pet
POST {{baseURL}}/pets
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "size": "SMALL",
  "independencyLevel": "LOW",
  "ageGroup": "PUPPY",
  "name": "Nalu",
  "city": "Caxias do Sul"
}